version: "3"
services:
  server:
    image: debian:bullseye-slim
    restart: unless-stopped
    container_name: server
    working_dir: /opt/app
    command: ./server
    volumes:
      - ./_build/bin/server:/opt/app/server
      - ./_build/lib:/opt/app/lib
    ports:
      - "9090:9090"
    environment:
      - LD_LIBRARY_PATH=/opt/app/lib

  client:
    image: python:3.9.12-slim-bullseye
    restart: on-failure
    container_name: client
    working_dir: /opt/app
    command: ./PythonClient.py
    volumes:
      - ./client/PythonClient.py:/opt/app/PythonClient.py
      - ./_build/client/gen-py:/opt/app/gen-py
      - ./.venv/:/opt/app/venv
    environment:
      - VIRTUAL_ENV=/opt/app/venv
      - PATH=/opt/app/venv/bin:/usr/bin:/bin
    depends_on:
      - server
